version: "3.8"

services:
  database:
    build: ./backend/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=backend_user
      - POSTGRES_PASSWORD=backend_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/backend_db
      - SPRING_DATASOURCE_USERNAME=backend_user
      - SPRING_DATASOURCE_PASSWORD=backend_password
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
